credentials:
  usernames:
    felipefischel:
      email: felipefischel@gmail.com
      name: Felipe
      password: $2b$12$.o1UqnVkw6qKweJ49odfbe1qb0MQcg6YP7orp/iuVVy2GiVshJXn2
cookie:
  expiry_days: 30
  key: k5J@hAg%aJow@f
  name: token
preauthorized:
  emails:
  - felipefischel@gmail.com
